In [78]:
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [69]:
df = pd.read_csv("C:\\Users\\sanja\\OneDrive\\Pictures\\All working files\\data\\Titanin_train.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.corr()

C:\Users\sanja\AppData\Local\Temp\ipykernel_7576\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.036847 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.077221 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.369226  0.083081  0.018443   
Age             0.036847 -0.077221 -0.369226  1.000000 -0.308247 -0.189119   
SibSp          -0.057527 -0.035322  0.083081 -0.308247  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.189119  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.096067  0.159651  0.216225   

                 Fare  
PassengerId  0.012658  
Survived     0.257307  
Pclass      -0.549500  
Age          0.096067  
SibSp        0.159651  
Parch        0.216225  
Fare         1.000000

In [70]:
df = df[['Fare','Pclass',"Survived"]]

In [71]:
df.head()

Fare  Pclass  Survived
0   7.2500       3         0
1  71.2833       1         1
2   7.9250       3         1
3  53.1000       1         1
4   8.0500       3         0

In [72]:
X = df.drop(columns=['Survived'],axis=1)
y = df['Survived']

In [73]:
X

Fare  Pclass
0     7.2500       3
1    71.2833       1
2     7.9250       3
3    53.1000       1
4     8.0500       3
..       ...     ...
886  13.0000       2
887  30.0000       1
888  23.4500       3
889  30.0000       1
890   7.7500       3

[891 rows x 2 columns]

In [80]:
L = LogisticRegression()
L.fit(X,y)

print(L.coef_)
print(L.intercept_)

[[ 0.00560965 -0.67625308]]
[0.87683918]


In [100]:
class LR:
    def __init__(self,lr,epoch):
        self.lr = lr
        self.epoch = epoch
    
    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))
     
    def train(self, X, y):
        self.X = np.insert(X.values,0,1,axis=1)
        self.y = y
        weights = np.ones(self.X.shape[1])
        for i in range(self.epoch):
            y_hat = self.sigmoid(np.dot(self.X,weights))
            weights = weights + self.lr*(np.dot((self.y-y_hat),self.X)/self.X.shape[0])
        return weights[1:], weights[0]

In [115]:
l = LR(lr=0.001,epoch=2500)
l.train(X,y)

(array([ 0.00606877, -0.46648804]), 0.4958432538848411)

[[ 0.00560965 -0.67625308]]
[0.87683918]

In [40]:
import numpy as np

class LR:
    def __init__(self, learning_rate=0.01, num_iterations=1000):
        self.learning_rate = learning_rate
        self.num_iterations = num_iterations
        self.weights = None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))



    def fit(self, X, y):
        # Add a bias term to X
        X_bias = np.c_[np.ones((X.shape[0], 1)), X]

        # Initialize weights
        self.weights = np.zeros(X_bias.shape[1])

        for _ in range(self.num_iterations):
            # Calculate the linear combination
            z = np.dot(X_bias, self.weights)
            # Pass through the sigmoid function
            y_hat = self.sigmoid(z)

            # Compute the gradient
            gradient = np.dot(X_bias.T, (y_hat - y)) / len(y)

            # Update weights using gradient descent
            self.weights -= self.learning_rate * gradient

        return self.weights

    def predict(self, X):
        # Add a bias term to X
        X_bias = np.c_[np.ones((X.shape[0], 1)), X]
        # Calculate the linear combination
        z = np.dot(X_bias, self.weights)
        # Pass through the sigmoid function
        y_hat = self.sigmoid(z)
        # Convert probabilities to binary predictions
        predictions = (y_hat >= 0.5).astype(int)
        return predictions
